#!/usr/bin/env python3
"""
PreToolUse hook — blocks writes to sensitive files.

Applies to ALL agents (coder, curator, anyone with Write/Edit). Blocks:
  - .env / .env.* files
  - .git/ internals
  - package-lock.json, yarn.lock, pnpm-lock.yaml (must be regenerated by package manager)
  - dist/ output
  - node_modules/
  - .claude/settings.json (hook config — security policy)

Exit 0 = allow, exit 2 = block (stderr returned to Claude as the reason).

Reference: matchers in settings.json filter this to Write/Edit/MultiEdit tools.
"""
import json
import sys
import re

BLOCKED_PATTERNS = [
    (re.compile(r"(^|/)\.env(\.|$)"),
     "Edits to .env files require explicit user approval. Surface the change you want and ask the user."),
    (re.compile(r"(^|/)\.git/"),
     "Direct edits to .git internals are forbidden. Use git commands via Bash if needed."),
    (re.compile(r"(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$"),
     "Lockfiles are managed by the package manager, not edited by hand. Run npm/yarn/pnpm install instead."),
    (re.compile(r"(^|/)node_modules/"),
     "node_modules/ is a build artifact and must not be edited."),
    (re.compile(r"(^|/)dist/"),
     "dist/ is a build artifact. Edit source under src/ and rebuild."),
    (re.compile(r"(^|/)\.next/"),
     ".next/ is a Next.js build artifact. Edit source under src/ and rebuild."),
    (re.compile(r"(^|/)\.claude/settings\.json$"),
     "Editing .claude/settings.json (hook config) requires explicit user approval — these are project security policies."),
]


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)  # malformed input — let it through; not our job

    tool_input = payload.get("tool_input", {})
    file_path = tool_input.get("file_path") or tool_input.get("path") or ""

    if not file_path:
        sys.exit(0)

    # Strip a literal leading "./" only — do NOT use lstrip("./"), which
    # would also strip leading dots from paths like ".env" or ".git/...".
    fp = re.sub(r"^\./", "", file_path)

    for pattern, reason in BLOCKED_PATTERNS:
        if pattern.search(fp):
            print(f"BLOCKED: {file_path}\nReason: {reason}", file=sys.stderr)
            sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
